### PR TITLE
Avoid returning -0.0 from distance_to_point_l1

### PR DESCRIPTION
**Pull request by ReubenHill**
-0.0 can be converted to a small negative number during code generation

### CODE REVIEW

**Comment by wence-** [comment]
> -0.0 can be converted to a small negative number during code generation

I agree that the distance should be positive, but what do you mean by this? I hope very much that no part of the codegen flushes _away_ from zero.

**Comment by wence-** [comment]
If you're using sympy then it doesn't see any actual values, no? Can you show the c code that `celldist_l1_c_expr` returns?

**Comment by ReubenHill** [comment]
```python
from firedrake import *
from firedrake.pointquery_utils import celldist_l1_c_expr
import tsfc

m = UnitIcosahedralSphereMesh()
ufl_coordinate_element = m.coordinates.ufl_element()
finat_element = tsfc.finatinterface.create_element(ufl_coordinate_element)
print(celldist_l1_c_expr(finat_element.cell, "X"))
```
produces
```
0.5*fabs(PetscRealPart(X[0])) + 0.5*fabs(PetscRealPart(X[1])) + 0.5*fabs(PetscRealPart(X[0]) + PetscRealPart(X[1]) - 1.0) - 0.5
```
on master and
```
fabs(0.5*fabs(PetscRealPart(X[0])) + 0.5*fabs(PetscRealPart(X[1])) + 0.5*fabs(PetscRealPart(X[0]) + PetscRealPart(X[1]) - 1.0) - 0.5)
```
here.

**Comment by wence-** [comment]
OK, so I agree that this change makes the result always positive. But perhaps I am being dumb, how does `-0` turn into a large negative number later?

**Comment by ReubenHill** [comment]
> OK, so I agree that this change makes the result always positive. But perhaps I am being dumb, how does `-0` turn into a large negative number later?

No you aren't being dumb I missed out a minus in the power! So I meant to write

> on very rare occasions, getting negative answers (-10^-16 or so)

**Comment by wence-** [comment]
My vague guess is that this is because the kernels are being compiled with `-ffast-math`, which subsumes `-fassociative-math`, allowing the compiler to reorder the order of computations.
e.g. consider:

```
x = 1e-17
y = 1 - 1.0/10.0 // 0.9090909090909091

In [61]: 0.5*abs(x) + 0.5*abs(y) + 0.5*abs(x + y - 1) - 0.5
Out[61]: 0.0

In [62]: 0.5*abs(x) + (0.5*abs(y) -0.5) + 0.5*abs(x + y - 1)
Out[62]: 6.938893903907228e-18

In [63]: 0.5*abs(x) + ((0.5*abs(y) -0.5) + 0.5*abs(x + y - 1))
Out[63]: 5e-18

In [64]: 0.5*abs(x) + (0.5*abs(y) -0.5) + 0.5*abs(x + (y - 1))
Out[64]: 0.0

In [65]: (0.5*abs(x) + 0.5*abs(y) -0.5) + 0.5*abs(x + (y - 1))
Out[65]: -6.938893903907228e-18
```

(The correct answer if you do things in reals for this case is 0).

So if the compiler decides to reorder to:

```
(0.5*abs(x) + 0.5*abs(y) - 0.5)  + 0.5*abs(x + (y - 1))
```
Then this function, which should have range $[0, \infty)$, can produce negative results.

I wonder if the better option is to clamp to the valid range (i.e. return `fmax(0, ...)`, rather than `fabs(...)`).

**Review by dham — APPROVED** [review]

**Pull request merged**
